FROM node:22-alpine as build

WORKDIR /src

COPY ./wtt_web_client/package.json ./package.json
COPY ./wtt_web_client/package-lock.json ./package-lock.json
RUN npm i

COPY ./wtt_web_client/src ./src
COPY ./wtt_web_client/typings ./typings
COPY ./wtt_web_client/public ./public
COPY ./wtt_web_client/tsconfig.json ./tsconfig.json
COPY ./wtt_web_client/declaration.d.ts ./declaration.d.ts
COPY ["./wtt_web_client/.env", "./.env"]
COPY ["./wtt_web_client/.env.development", "./.env.development"]
COPY ["./wtt_web_client/.env.production", "./.env.production"]

RUN npm run build



FROM nginx:alpine as final

WORKDIR /usr/share/nginx/html
RUN rm -rf *

COPY --from=build /src/build /usr/share/nginx/html
COPY ./wtt_web_client/build_alpine/pre-nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]