services:
  database:
    restart: always
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: OVERRIDE_ME
      POSTGRES_DB: wtt_db
    volumes:
      - vdb_main_server_database:/var/lib/postgresql/data/

  main_server:
    restart: always
    image: luminodiode/wtt_main_server_api
    build: 
      dockerfile: ./dockerfile_backend
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    secrets:
      - source: backend_secrets
        target: /etc/wtt/secrets.json
    ports:
      - 6030:8080/tcp

  web_client:
    restart: always
    image: luminodiode/wtt_web_client
    build: 
      dockerfile: ./dockerfile_frontend
    depends_on:
      - main_server
    ports:
      - 6031:3000/tcp

secrets:
  backend_secrets:
    file: ./secrets.json
    
volumes:
  vdb_main_server_database:
    external: false