// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi.Database;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(WttContext))]
    [Migration("20240624202715_init5")]
    partial class init5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Database.Common.DbEmailSendLog", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Addressee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSucceeded")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.ToTable("EmailSendLogs");
                });

            modelBuilder.Entity("Models.Database.Common.DbUser", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("EmailConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<DateTime>("PasswordLastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<string>("RegistrationCity")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationCountry")
                        .HasColumnType("text");

                    b.Property<IPAddress>("RegistrationIPAddress")
                        .HasColumnType("inet");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<byte[]>("TotpSecretKeyForSha512")
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.HasKey("Guid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.Database.Infrastructure.RecoveryJwt", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<IPAddress>("IPAddress")
                        .HasColumnType("inet");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("JtiSha512")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<DateTime>("OriginIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.ToTable("RecoveryJwts");
                });

            modelBuilder.Entity("Models.Database.Infrastructure.RefreshJwt", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<IPAddress>("IPAddress")
                        .HasColumnType("inet");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("JtiSha512")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<DateTime>("OriginIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.ToTable("RefreshJwts");
                });

            modelBuilder.Entity("Models.Database.RunningScenarios.DbScenarioRun", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Dictionary<string, string>>("InputValues")
                        .HasColumnType("hstore");

                    b.Property<bool?>("IsSucceeded")
                        .HasColumnType("boolean");

                    b.Property<Dictionary<string, string>>("OutputValues")
                        .HasColumnType("hstore");

                    b.Property<TimeSpan?>("ProcessorTime")
                        .HasColumnType("interval");

                    b.Property<int?>("RunReason")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScenarioGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("ScenarioJsonResult")
                        .HasColumnType("jsonb");

                    b.Property<string>("ScenarioJsonSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Guid");

                    b.ToTable("ScenarioRuns");
                });

            modelBuilder.Entity("Models.Database.TestScenarios.DbTestScenario", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string[]>("ArgNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int[]>("ArgTypes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime?>("Changed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnableEmailNotifications")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EntryPoint")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RunIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<TimeOnly[]>("RunTimes")
                        .HasColumnType("time without time zone[]");

                    b.Property<Guid?>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.ToTable("TestScenarios");
                });
#pragma warning restore 612, 618
        }
    }
}
