// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using wtt_main_server_api.Database;

#nullable disable

namespace wtt_main_server_api.Migrations
{
    [DbContext(typeof(WttContext))]
    partial class WttContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("ADbObjectWithGuidSequence");

            modelBuilder.Entity("webooster.DataModels.ADbObjectWithGuid", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"ADbObjectWithGuidSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<long>("Id"));

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("wtt_main_server_data.Database.Common.DbEmailSendLog", b =>
                {
                    b.HasBaseType("webooster.DataModels.ADbObjectWithGuid");

                    b.Property<string>("Addressee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSucceeded")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RelatedUserGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.ToTable("EmailSendLogs");
                });

            modelBuilder.Entity("wtt_main_server_data.Database.Common.DbUser", b =>
                {
                    b.HasBaseType("webooster.DataModels.ADbObjectWithGuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("EmailConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<DateTime>("PasswordLastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<byte[]>("TotpSecretKeyForSha512")
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("wtt_main_server_data.Database.Infrastructure.DbJwtIdentifier", b =>
                {
                    b.HasBaseType("webooster.DataModels.ADbObjectWithGuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<IPAddress>("IPAddress")
                        .HasColumnType("inet");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("JtiSha512")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<DateTime>("OriginIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RelatedUserGuid")
                        .HasColumnType("uuid");

                    b.ToTable("DbJwtIdentifier");
                });

            modelBuilder.Entity("wtt_main_server_data.Database.Networking.DbUserImapAccount", b =>
                {
                    b.HasBaseType("webooster.DataModels.ADbObjectWithGuid");

                    b.Property<string>("ConnectionUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedUserGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("UserImapAccounts");
                });

            modelBuilder.Entity("wtt_main_server_data.Database.Networking.DbUserProxy", b =>
                {
                    b.HasBaseType("webooster.DataModels.ADbObjectWithGuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedUserGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("UserProxies");
                });

            modelBuilder.Entity("wtt_main_server_data.Database.TestScenarios.DbTestScenario", b =>
                {
                    b.HasBaseType("webooster.DataModels.ADbObjectWithGuid");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string[]>("ArgNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int[]>("ArgTypes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("ChangeDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EnableEmailNotifications")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EntryPoint")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedUserGuid")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Sha512")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.ToTable("TestScenarios");
                });

            modelBuilder.Entity("wtt_main_server_data.Database.Networking.DbImapAccount", b =>
                {
                    b.HasBaseType("wtt_main_server_data.Database.Networking.DbUserImapAccount");

                    b.Property<int>("SubscriptionRequired")
                        .HasColumnType("integer");

                    b.ToTable("ImapAccounts");
                });

            modelBuilder.Entity("wtt_main_server_data.Database.Networking.DbProxy", b =>
                {
                    b.HasBaseType("wtt_main_server_data.Database.Networking.DbUserProxy");

                    b.Property<int>("SubscriptionRequired")
                        .HasColumnType("integer");

                    b.ToTable("Proxies");
                });
#pragma warning restore 612, 618
        }
    }
}
