FROM node:22-alpine as build

WORKDIR /src

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
RUN npm i

COPY ./src ./src
COPY ./typings ./typings
COPY ./public ./public
COPY ./tsconfig.json ./tsconfig.json
COPY ./declaration.d.ts ./declaration.d.ts
COPY ["./.env", "./.env"]
COPY ["./.env.development", "./.env.development"]
COPY ["./.env.production", "./.env.production"]

RUN npm run build

CMD "echo 123"



# FROM nginx:alpine as final

# WORKDIR /usr/share/nginx/html
# RUN rm -rf *

# COPY --from=build /src/build /usr/share/nginx/html
# COPY ./build_alpine/pre-nginx.conf /etc/nginx/nginx.conf

# CMD ["nginx", "-g", "daemon off;"]